### ISSUE TITLE
ACS Race data missing at tract level

### ISSUE THREAD

**Issue by mkfreeman** [DataUSA/datausa-api#15]
I'm attempting to get the percentage the population that is white (`pop_white`) at the tract level for **all tracts in a particular city**. The following [query](https://api.datausa.io/api/?show=geo&sumlevel=tract&force=acs_5yr.yg_race&limit=5) returns an empty array of data:

`https://api.datausa.io/api/?show=geo&sumlevel=tract&force=acs_5yr.yg_race&limit=5`

However, the `pop_white` data appears to be visible at the [state level](https://api.datausa.io/api/?show=geo&sumlevel=state&required=pop_white&limit=10). 

I'm able to get population data at the tract level ([link](http://api.datausa.io/api/?show=geo&sumlevel=tract&required=pop&year=latest&geo=31000US42660)), but **tract level data appears to be unavailable**.

**Comment by jspeis** [comment]
@mkfreeman thanks for reporting this. Since we did not have a visualization on the profile pages for yg_race tract-level data, this data did not end up in our database (so currently it's bug that the table says that it supports the tract sumlevel) . But since we are currently in the process of updating our ACS to 2015 anyway - I've just written some code to pull this data in so we'll have it in our API as part of our next data release!

**Comment by mkfreeman** [comment]
Thanks much, @jspeis! Do you know when the release is schedule for, and/or would it be possible to get access to that information (the code you wrote) in advance?

**Comment by jspeis** [comment]
Sure, no problem @mkfreeman. If you send an e-mail to <img width="161" alt="screen shot 2017-01-25 at 10 30 31 am" src="https://cloud.githubusercontent.com/assets/87581/22296807/53dca1e2-e2e9-11e6-955a-44b130ee2557.png"> I can share a link to our test server.
