### ISSUE TITLE
show=cip,naics data call not working

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-api#22]
https://sunbird-api.datausa.io/api/?show=cip,naics&required=num_ppl&sumlevel=all,all&year=all

**Comment by jspeis** [comment]
This behavior is intentional at the moment, since the PUMS tables only support two digit CIPs (and not "all" CIPS: 2,4,6). That said, I'm open to having "all" in this case return the 2-digit CIPs but initially I was thinking that could have been a source of confusion for users of the API expecting to get data on all CIP codes.

**Comment by davelandry** [comment]
I think we should return what we have, and if anyone questions it we can refer them to the supported sumlevels dictionary that is passed in the data call :-)

**Comment by jspeis** [comment]
The origin call you tried should now work
