### ISSUE TITLE
bea api not working

### ISSUE THREAD

**Issue by shalmalijain** [DataUSA/datausa-api#25]
https://api.datausa.io/api/join/?required=year,industry_iocode,commodity_iocode,value_millions,industry_level&show=geo&limit=500 this api caall gives an error. It says {"error": "No tables can match the specified query."}. Please help.

**Comment by jspeis** [comment]
The reason you received an error is that the BEA data in Data USA is not broken out by geography. The following call would work:

https://api.datausa.io/api/join/?required=year,industry_iocode,commodity_iocode,value_millions,industry_level&show=commodity_iocode&limit=500&sumlevel=all

(See the API results for a list of supported sumlevels for commodity_iocode and industry_iocode)

**Comment by shalmalijain** [comment]
Thanks

**Comment by shalmalijain** [comment]
Can you help me out with another API? 

I get an error: {"error": "Unknown PG numeric type: 25"} for the following API. What am I missing?

https://api.datausa.io/api/join/?show=cip&required=grads_total,grads_men,grads_women,grads_native,grads_native_men,grads_native_women,grads_asian,grads_asian_men,grads_asian_women,grads_black,grads_black_men,grads_black_women,grads_hispanic,grads_hispanic_men,grads_hispanic_women,grads_hawaiian,grads_hawaiian_men,grads_hawaiian_women,grads_white,grads_white_men,grads_white_women,grads_multi,grads_multi_men,grads_multi_women,grads_unknown,grads_unknown_men,grads_unknown_women,grads_nonresident,grads_nonresident_men,grads_nonresident_women,year,grads_total_growth,grads_total_rca,cip,degree&limit=500

**Comment by jspeis** [comment]
@shalmalijain thank you for reporting this issue, the error you see was caused by an issue with the field `grads_total_growth` in one table in the database. This  has now been fixed in the development server and will be reflected in our next update. In the meantime, if you re-run your query without that one field it will work:

https://api.datausa.io/api/join/?show=cip&required=grads_total,grads_men,grads_women,grads_native,grads_native_men,grads_native_women,grads_asian,grads_asian_men,grads_asian_women,grads_black,grads_black_men,grads_black_women,grads_hispanic,grads_hispanic_men,grads_hispanic_women,grads_hawaiian,grads_hawaiian_men,grads_hawaiian_women,grads_white,grads_white_men,grads_white_women,grads_multi,grads_multi_men,grads_multi_women,grads_unknown,grads_unknown_men,grads_unknown_women,grads_nonresident,grads_nonresident_men,grads_nonresident_women,year,grads_total_rca,cip,degree&limit=500

**Comment by shalmalijain** [comment]
Ok. Thanks a lot for the help.
