### ISSUE TITLE
add "keywords" column to university attribute table and hook it up to search

### ISSUE THREAD

**Issue by davelandry** [DataUSA/datausa-api#35]
- [x] add table column
- [x] hook up to search
- [x] rebuild index script

**Comment by jspeis** [comment]
This is pretty much hooked up, and now all profile attribute kinds can have alias keywords in the database. But note that because of the way search is implemented in Data USA using `whoosh`, the underlying search index will need to be rebuilt after changes are made to the table. I'll add a helper script in the API repo that will rebuild the search index to reflect the latest changes.
